package http

type headers struct {
	Accept              string
	AcceptCharset       string
	AcceptEncoding      string
	AcceptLanguage      string
	AcceptDatetime      string
	Authorization       string
	CacheControl        string
	Connection          string
	Cookie              string
	ContentLength       string
	ContentMD5          string
	ContentType         string
	Date                string
	Expect              string
	Forwarded           string
	From                string
	Host                string
	IfMatch             string
	IfModifiedSince     string
	IfNoneMatch         string
	IfRange             string
	MaxForwards         string
	Origin              string
	Pragma              string
	ProxyAuthorization  string
	Range               string
	Referer             string
	TE                  string
	UserAgent           string
	Upgrade             string
	Via                 string
	Warning             string
	XRequestedWith      string
	DNT                 string
	XForwardedFor       string
	XForwardedHost      string
	XForwardedProto     string
	FrontEndHttps       string
	XHttpMethodOverride string
	XATTDeviceId        string
	XWapProfile         string
	ProxyConnection     string
	XUIDH               string
	XCsrfToken          string
	XRequestID          string
	XCorrelationID      string
	RefreshToken        string
	TwoFactorToken      string
	CsrfToken           string
}

var Headers = headers{
	Accept:              "Accept",
	AcceptCharset:       "Accept-Charset",
	AcceptEncoding:      "Accept-Encoding",
	AcceptLanguage:      "Accept-Language",
	AcceptDatetime:      "Accept-Datetime",
	Authorization:       "Authorization",
	CacheControl:        "Cache-Control",
	Connection:          "Connection",
	Cookie:              "Cookie",
	ContentLength:       "Content-Length",
	ContentMD5:          "Content-MD5",
	ContentType:         "Content-Type",
	Date:                "Date",
	Expect:              "Expect",
	Forwarded:           "Forwarded",
	From:                "From",
	Host:                "Host",
	IfMatch:             "If-Match",
	IfModifiedSince:     "If-Modified-Since",
	IfNoneMatch:         "If-None-Match",
	IfRange:             "If-Range",
	MaxForwards:         "Max-Forwards",
	Origin:              "Origin",
	Pragma:              "Pragma",
	ProxyAuthorization:  "Proxy-Authorization",
	Range:               "Range",
	Referer:             "Referer",
	TE:                  "TE",
	UserAgent:           "User-Agent",
	Upgrade:             "Upgrade",
	Via:                 "Via",
	Warning:             "Warning",
	XRequestedWith:      "X-Requested-With",
	DNT:                 "DNT",
	XForwardedFor:       "X-Forwarded-For",
	XForwardedHost:      "X-Forwarded-Host",
	XForwardedProto:     "X-Forwarded-Proto",
	FrontEndHttps:       "Front-End-Https",
	XHttpMethodOverride: "X-Http-Method-Override",
	XATTDeviceId:        "X-ATT-DeviceId",
	XWapProfile:         "X-Wap-Profile",
	ProxyConnection:     "Proxy-Connection",
	XUIDH:               "X-UIDH",
	XCsrfToken:          "X-Csrf-Token",
	XRequestID:          "X-Request-ID",
	XCorrelationID:      "X-Correlation-ID",
	RefreshToken:        "Refresh-Token",
	TwoFactorToken:      "Two-Factor-Token",
	CsrfToken:           "X-Csrf-Token",
}
